use fastrand::Rng;
use std::env;
use std::io::Read;

/// The arithmetic operators our language supports.
#[derive(Debug)]
enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
}

/// Our little programming language.
#[derive(Debug)]
enum Expr {
    Binary(BinOp, Box<Expr>, Box<Expr>),
    Literal(i64),
}

impl Expr {
    /// Evaluate the expression.
    fn interp(&self) -> i64 {
        match self {
            Expr::Binary(op, lhs, rhs) => {
                let lhs = lhs.interp();
                let rhs = rhs.interp();
                match op {
                    BinOp::Add => lhs.wrapping_add(rhs),
                    BinOp::Sub => lhs.wrapping_sub(rhs),
                    BinOp::Mul => lhs.wrapping_mul(rhs),
                    BinOp::Div => lhs.checked_div(rhs).unwrap_or(0),
                }
            }
            Expr::Literal(num) => *num,
        }
    }
}

/// A parser for our language.
///
/// Requires fully parenthesized syntax, like (1*2)+(3-4).
struct Parser<'a> {
    buf: &'a str,
}

impl<'a> Parser<'a> {
    fn new(buf: &'a str) -> Self {
        Self { buf }
    }

    fn consume(&mut self, char_pred: fn(char) -> bool) -> Option<char> {
        let first = self.buf.chars().next()?;
        if char_pred(first) {
            self.buf = &self.buf[first.len_utf8()..];
            Some(first)
        } else {
            None
        }
    }

    fn skip_whitespace(&mut self) {
        while self
            .consume(|c| c == ' ' || c == '\n' || c == '\t')
            .is_some()
        {}
    }

    fn parse_digits(&mut self) -> Option<i64> {
        let first = self.consume(|c| c.is_ascii_digit())?; // Require at least one digit.
        let mut num = first as i64 - b'0' as i64;
        while let Some(digit) = self.consume(|c| c.is_ascii_digit()) {
            num = num * 10 + (digit as i64 - b'0' as i64);
        }
        Some(num)
    }

    fn parse_int(&mut self) -> Option<i64> {
        let negative = self.consume(|c| c == '-').is_some();
        let digits = self.parse_digits()?;
        Some(if negative { -digits } else { digits })
    }

    fn parse_expr(&mut self) -> Option<Expr> {
        let lhs = self.parse_term()?;
        self.skip_whitespace();
        let op = match self.consume(|c| c == '+' || c == '-' || c == '*' || c == '/') {
            Some(c) => match c {
                '+' => BinOp::Add,
                '-' => BinOp::Sub,
                '*' => BinOp::Mul,
                '/' => BinOp::Div,
                _ => unreachable!(),
            },
            None => {
                return Some(lhs);
            }
        };
        self.skip_whitespace();
        let rhs = self.parse_term()?;
        Some(Expr::Binary(op, Box::new(lhs), Box::new(rhs)))
    }

    fn parse_term(&mut self) -> Option<Expr> {
        if self.consume(|c| c == '(').is_some() {
            self.skip_whitespace();
            let expr = self.parse_expr()?;
            self.skip_whitespace();
            self.consume(|c| c == ')')?;
            Some(expr)
        } else {
            self.parse_int().map(Expr::Literal)
        }
    }

    fn parse(buf: &str) -> Option<Expr> {
        let mut parser = Parser::new(buf);
        parser.skip_whitespace();
        let res = parser.parse_expr()?;
        parser.skip_whitespace();
        if parser.buf.is_empty() {
            Some(res)
        } else {
            None
        }
    }
}

/// A random program generator.
struct Generator {
    rng: Rng,
}

impl Generator {
    fn new(seed: u64) -> Self {
        Self {
            rng: Rng::with_seed(seed),
        }
    }

    fn default() -> Self {
        Self { rng: Rng::new() }
    }

    /// Generate a random expression.
    ///
    /// The expression is a literal with probability 1/`lit_prob_inv`, and a binary expression
    /// otherwise. When we generate a binary expression, the two subtrees have double the
    /// probability of generating literals.
    ///
    /// I am not very good at statistics, but I think the expected tree size is `lit_prob_inv`.
    /// Let s(i) be the size of a tree generated by `gen(i)` (i.e., i is a shorthand for
    /// `lit_prob_env`). s(i) is of course a random variable:
    ///
    ///     s(i) = 1                    with probability 1/i
    ///     s(i) = 1 + s(i/2) + s(i/2)  with probability 1-1/i
    ///
    /// I think it's correct to say that the expected size is therefore:
    ///
    ///     E[s(i)] = (1/i) * 1 + (1-1/i) * (1 + E[s(i/2)] + E[s(i/2)])
    ///
    /// To simplify notation, let e(i) be the expected size, i.e., E[s(i)]. Then we have the
    /// recurrence:
    ///
    ///     e(i) = 1/i + (1-1/i) * (1 + 2*e(i/2))
    ///
    /// My claim above is that e(i) = i. We can confirm that this solves the recurrence (for i>0):
    ///
    ///     i = 1/i + (1-1/i) * (1 + 2*(i/2))
    ///     i = 1/i + (1-1/i) * (1 + i)
    ///     i = 1/i + 1 + i - 1/i - i/i
    ///     i = i
    ///
    /// Anecdotally, this also seems to be the right ballpark in practice.
    fn generate(&mut self, lit_prob_inv: u32) -> Expr {
        if self.rng.u32(0..lit_prob_inv) == 0 {
            Expr::Literal(self.rng.i64(0..100))
        } else {
            let lhs = Box::new(self.generate(lit_prob_inv / 2));
            let rhs = Box::new(self.generate(lit_prob_inv / 2));
            let op = match self.rng.u8(0..4) {
                0 => BinOp::Add,
                1 => BinOp::Sub,
                2 => BinOp::Mul,
                3 => BinOp::Div,
                _ => unreachable!(),
            };
            Expr::Binary(op, lhs, rhs)
        }
    }
}

/// Pretty-printing for expressions.
impl std::fmt::Display for Expr {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Expr::Binary(op, lhs, rhs) => {
                let op = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                };
                write!(f, "({} {} {})", lhs, op, rhs)
            }
            Expr::Literal(num) => write!(f, "{}", num),
        }
    }
}

/// Parse the program from stdin.
fn parse_stdin() -> std::io::Result<Expr> {
    let mut buffer = String::new();
    std::io::stdin().read_to_string(&mut buffer)?;
    let expr = Parser::parse(&buffer).expect("syntax error");
    Ok(expr)
}

/// Generate a random program, with an optional seed taken from the second argv position.
fn generate() -> Expr {
    let seed = env::args().nth(2);
    let mut genr = match seed {
        Some(s) => Generator::new(s.parse().expect("seed must be a number")),
        None => Generator::default(),
    };
    genr.generate(100_000_000)
}

/// An extremely simple CLI. The commands are:
///
/// * `interp`: Read a program from stdin and run it.
/// * `pretty`: Read a program from stdin and print it back out on stdout.
/// * `gen [SEED]`: Generate a random program and print it out on stdout.
/// * `gen_interp [SEED]`: Generate a random program and run it.
fn main() {
    let mode = env::args().nth(1).unwrap_or_else(|| "interp".to_string());
    match mode.as_str() {
        "interp" => {
            let expr = parse_stdin().unwrap();
            println!("{}", expr.interp());
            #[cfg(feature = "nofree")]
            std::mem::forget(expr);
        }
        "pretty" => {
            let expr = parse_stdin().unwrap();
            println!("{}", expr);
            #[cfg(feature = "nofree")]
            std::mem::forget(expr);
        }
        "gen" => {
            let expr = generate();
            println!("{}", expr);
            #[cfg(feature = "nofree")]
            std::mem::forget(expr);
        }
        "gen_interp" => {
            let expr = generate();
            println!("{}", expr.interp());
            #[cfg(feature = "nofree")]
            std::mem::forget(expr);
        }
        _ => {
            eprintln!("unknown mode: {}", mode);
        }
    }
}
