WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

// Entry point.
expr = _{ SOI ~ addExprW ~ EOI }

// Tokens.
number = @{ ASCII_DIGIT+ }
addOp = _{ add | sub }
    add = { "+" }
    sub = { "-" }
mulOp = _{ mul | div }
    mul = { "*" }
    div = { "/" }

// Expressions.
addExprW = _{ addExpr | mulExprW }
    addExpr = { term ~ addOp ~ addExprW }
mulExprW = _{ mulExpr | term }
    mulExpr = { term ~ mulOp ~ mulExprW }
term = _{ number | "(" ~ addExprW ~ ")" }
